export const pokemonai = [
    {
        src: '../img/charmander.png',
        pavadinimas: 'Charmander',
        spalva: 'Orange',
        nuoroda: 'https://www.pokemon.com/us/pokedex/charmander',
        forma: 'Lizard',
        tipas: 'Fire',
    },
    {
        src: '../img/balbasaur.png',
        pavadinimas: 'Bulbasaur',
        spalva: 'Green',
        nuoroda: 'https://www.pokemon.com/us/pokedex/bulbasaur',
        forma: 'Seed',
        tipas: 'Grass, Poison',
    },
    {
        src: '../img/ivysaur.png',
        pavadinimas: 'Ivysaur',
        spalva: 'Blue',
        nuoroda: 'https://www.pokemon.com/us/pokedex/ivysaur',
        forma: 'Seed',
        tipas: 'Grass, Poison',
    },
    {
        src: '../img/venusaur.png',
        pavadinimas: 'Venusaur',
        spalva: 'Blue',
        nuoroda: 'https://www.pokemon.com/us/pokedex/venusaur',
        forma: 'Seed',
        tipas: 'Grass, Poison',
    },
    {
        src: '../img/charmeleon.png',
        pavadinimas: 'Charmeleon',
        spalva: 'Orange',
        nuoroda: 'https://www.pokemon.com/us/pokedex/charmeleon',
        forma: 'Flame',
        tipas: 'Fire',
    },
    {
        src: '../img/charizard.png',
        pavadinimas: 'Charizard',
        spalva: 'Orange',
        nuoroda: 'https://www.pokemon.com/us/pokedex/charizard',
        forma: 'Flame',
        tipas: 'Fire, Flying',
    },
    {
        src: '../img/squirtle.png',
        pavadinimas: 'Squirtle',
        spalva: 'Blue',
        nuoroda: 'https://www.pokemon.com/us/pokedex/squirtle',
        forma: 'Tiny Turtle',
        tipas: 'Water',
    },
    {
        src: '../img/wartortle.png',
        pavadinimas: 'Wartortle',
        spalva: 'Blue',
        nuoroda: 'https://www.pokemon.com/us/pokedex/wartortle',
        forma: 'Turtle',
        tipas: 'Water',
    },
    {
        src: '../img/blastoise.png',
        pavadinimas: 'Blastoiser',
        spalva: 'Blue, Brown',
        nuoroda: 'https://www.pokemon.com/us/pokedex/blastoise',
        forma: 'Shellfish',
        tipas: 'Water',
    },
    {
        src: '../img/caterpie.png',
        pavadinimas: 'Caterpie',
        spalva: 'Green',
        nuoroda: 'https://www.pokemon.com/us/pokedex/caterpie',
        forma: 'Worm',
        tipas: 'Bug',
    },
];